version: '3'

services:
  php-7.3:
    image: nfqlt/php73-fpm
    volumes:
      - ../apollof:/srv/www/apollof
    networks:
      - mynetwork
    # environment:
    #   - PHP_EXTENSIONS=redis.so

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../apollof:/srv/www/apollof
      - ./nginx-config:/etc/nginx/conf.d  # Map the local folder to Nginx config folder
    depends_on:
      - php-7.3
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appolo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql_data:
